name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - test  # Adjust this to the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Decode GCP Credentials
      run: echo "${{ secrets.GCP_SA_KEY }}" | base64 -d > gcp-key.json

    - name: Set up Google Cloud Platform
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key_file: gcp-key.json
        export_default_credentials: true

    - name: Build and Push Docker image
      run: |
        gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/mltest:latest

    - name: Deploy to Google Cloud Run
      run: |
        gcloud run deploy mlservice \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/mltest1:latest \
          --platform managed \
          --region ${{ secrets.GCP_REGION }} \
          --allow-unauthenticated
